# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-09-23 21:34
from __future__ import unicode_literals

import datetime
from pony import orm

dependencies = []

def define_entities(db):
    class User(db.Entity):
        username = orm.Optional(str, unique=True)
        password_hash = orm.Optional(str)
        email = orm.Required(str, unique=True)
        dt_registered = orm.Optional(datetime.datetime)
        dt_last_visit = orm.Optional(datetime.datetime)
        verified = orm.Optional(bool)
        failed_login = orm.Optional(int)
        last_failed_login = orm.Optional(datetime.datetime)
