# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-09-23 21:51
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0001_initial']

operations = [
    op.AddEntity('Ship', ['Entity'], [('id', orm.PrimaryKey(int, auto=True)), ('no', orm.Optional(bool)), ('yes', orm.Optional(bool))]),
    op.AddRelation('Ship', 'user', orm.Optional('User'), 'ships', orm.Set('Ship'))]
