# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-09-23 22:50
from __future__ import unicode_literals

import datetime
from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0002_2018-09-23_21-51-50']

operations = [
    op.AddAttr('Ship', 'dt_shipped', orm.Optional(datetime.datetime))]
